import os
import re
import pandas as pd

# --- Configuration ---
# Path to the summary file generated by the inference script
SUMMARY_PATH = r"inference_results_cleaned\summary_cleaned.txt"
# Destination path for the final formatted spreadsheet
OUTPUT_CSV = r"inference_results_cleaned\Final_Quantification_Table.csv"

def run_post_analysis():
    """
    Parses the inference log and reshapes the data into a wide-format table
    suitable for direct inclusion in manuscripts or statistical software.
    """
    if not os.path.exists(SUMMARY_PATH):
        print(f"Error: Summary file not found at {SUMMARY_PATH}")
        return

    raw_measurements = []

    print(f"Reading inference summary and restructuring data: {SUMMARY_PATH}")

    # 1. Parse the summary text file
    with open(SUMMARY_PATH, 'r', encoding='utf-8') as f:
        for line in f:
            # Regex to match: Img[PhotoID]_[PadID].png: [Count] glands, [Area] mm2
            # Groups: 1=PhotoIndex, 2=PadIndex, 3=GlandCount, 4=PhysicalArea
            regex_pattern = r'Img(\d+)_(\d+)\.png:\s+(\d+)\s+glands,\s+([\d\.]+)\s+mm2'
            match = re.search(regex_pattern, line)

            if match:
                photo_idx = int(match.group(1))
                pad_idx = int(match.group(2))
                gland_count = int(match.group(3))
                physical_area = float(match.group(4))

                raw_measurements.append({
                    'Photo_ID': photo_idx,
                    'Pad_ID': pad_idx,
                    'Count': gland_count,
                    'Area': physical_area
                })

    if not raw_measurements:
        print("Error: No valid data found. Check if summary format matches '... glands, ... mm2'.")
        return

    # 2. Reshape data into Wide Format
    # Creates one row per Photo with separate columns for each Pad's Count and Area
    df = pd.DataFrame(raw_measurements)

    # Pivot Count and Area data separately
    pivot_count = df.pivot(index='Photo_ID', columns='Pad_ID', values='Count').add_prefix('Pad').add_suffix('_Count')
    pivot_area = df.pivot(index='Photo_ID', columns='Pad_ID', values='Area').add_prefix('Pad').add_suffix('_Area')

    # Merge into a single comprehensive table
    final_report = pd.concat([pivot_count, pivot_area], axis=1)

    # 3. Organize columns by Pad sequence (Pad1_Count, Pad1_Area, Pad2_Count, Pad2_Area...)
    ordered_columns = []
    for i in range(1, 7):
        ordered_columns.extend([f'Pad{i}_Count', f'Pad{i}_Area'])

    # Ensure only existing columns are included to prevent errors
    existing_columns = [col for col in ordered_columns if col in final_report.columns]
    final_report = final_report[existing_columns].reset_index()

    # 4. Display Preview and Save to Disk
    print("\n" + "="*90)
    print("                      JHU iOIV - Sweat Gland Quantification Report")
    print("="*90)
    print(final_report.to_string(index=False))
    print("="*90)

    final_report.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[Success] Formatted table generated at: {OUTPUT_CSV}")

if __name__ == "__main__":
    run_post_analysis()